# -*- coding: utf-8 -*-
"""CE507-HW6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Fi18wkCS4h3DHZjTqUHc46pcYq7Pktr5

# Problem 1
"""

#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Sep 23 11:45:50 2024

@author: kendrickshepherd
"""

import sys
import numpy as np
import math
import matplotlib
from matplotlib import pyplot as plt

# IMPORT (or copy) your code from HW3 here
# which evaluated a Lagrane polynomial basis function

## Code From HW 3 ##

# Given a set of points, pts, to interpolate
# and a polynomial degree, this function will
# evaluate the a-th basis function at the
# location xi

def LagrangeBasisEvaluation(p,pts,xi,a):
    # ensure valid input
    if (p+1 != len(pts)):
        sys.exit("The number of input points for interpolating must be the same as one plus the polynomial degree for interpolating")

    # ensure 'pts' is unique and in ascending order
    pts_unique = sorted(set(pts))

    val = 1
    for b in range(0,p+1):
        if b != a:
            val *= (xi-pts_unique[b])/(pts_unique[a]-pts_unique[b])
    return val

    # complete this code and return an appropriate value
    # as given in Hughes Equation 3.6.1

# Plot the Lagrange polynomial basis functions
# COMMENT THIS CODE
def PlotLagrangeBasisFunctions(p,pts,n_samples = 101):

    # ensure 'pts' is unique and in ascending order
    pts_unique = sorted(set(pts))

    # Makes 'xis' into 101 evenly spaced intervals starting at the minimum value
    # in the list 'pts' and ending at the maximum value of 'pts'
    xis = np.linspace(min(pts),max(pts),n_samples)
    # Creates a single figure with a single set of axes.
    fig, ax = plt.subplots()
    # Starts a 'for' loop that will march the variable 'a' from zero to 'p+1'
    # where 'p+1' is the polynomial degree + 1
    for a in range(0,p+1):
        # Creates an empty list called 'vals'
        vals = []
        # Starts a 'for' loop where the variable 'xi' is marched through each
        # interval of 'xis'
        for xi in xis:
            # Since 'vals' is an empty list, this builds a list of the output
            # from the 'LagrangeBasisEvaluation' equation, which computes the
            # value of the lagrange basis polynomial of degree 'a' at 'xi'
            vals.append(LagrangeBasisEvaluation(p, pts, xi, a))
        # Generates a plot where 'xis' is the x-value and 'vals' is the y-value
        plt.plot(xis,vals)
    # Adds a dashed grid to the plot generated previously
    ax.grid(linestyle='--')

# Interpolate two-dimensional data
def InterpolateFunction(p,pts2D,n_samples = 101):
    # Insert appropriate text here, as described
    # in the homework prompt

    # Separate the 'pts2D' array into x and y coordinates
    pts = pts2D[:,0]
    coeffs = pts2D[:,1]

    # Create an evenly distributed list of the x coordinates ('pts')
    xis = np.linspace(min(pts),max(pts),n_samples)

    # Create an array of zeros in the same dimension as xis
    ys = np.zeros(len(xis))

    # Create a for loop that goes through every index in the list xis then
    # extract the i-th value of xis
    for i in range(len(xis)):
      xi = xis[i]
      L = 0
      # Create a nested for loop to evaluate every p+1 of the Lagrange polynomial
      # basis functions at point xi
      for a in range(min(pts),p+1):
        LBE = LagrangeBasisEvaluation(p,pts,xi,a)
        L += LBE * coeffs[a]
      # Multiply the value of the basis function evaluated at xi by its corresponding
      # y coefficient from 'coeffs'. Add this quantity into the 'ys' value corresponding
      # to index xi
      ys[i] += L

    fig, ax = plt.subplots()
    plt.plot(xis,ys)
    plt.scatter(pts, coeffs,color='r')



## ^^Code From HW 3^^ ##



# higher-dimensional basis function with multi-index
def MultiDimensionalBasisFunctionIdxs(idxs,degs,interp_pts,xis):
    x = 0
    for a in range(0,degs+1):
        x += spatial_pts[a] * LagrangeBasisEvaluation(degs,interp_pts,xis,a)
    return

# higher-dimensional basis function with single index
def MultiDimensionalBasisFunction(A,degs,interp_pts,xis):
    multi_indxs = []
    for i in range(len(degs)):
        multi_indxs.append(A % degs[i])
        A = A // degs[i]

    val = 1
    for i in range(0,len(multi_indxs)):
        val *= LagrangeBasisEvaluation(degs[i],interp_pts[i],xis[i],multi_indxs[i])
    return val

# plot of 2D basis functions with A a single index
def PlotTwoDimensionalParentBasisFunction(A,degs,npts = 101,contours = True):
    interp_pts = [np.linspace(-1,1,degs[i]+1) for i in range(0,len(degs))]
    xivals = np.linspace(-1,1,npts)
    etavals = np.linspace(-1,1,npts)

    Xi,Eta = np.meshgrid(xivals,etavals)
    Z = np.zeros(Xi.shape)

    for i in range(0,len(xivals)):
        for j in range(0,len(etavals)):
            Z[i,j] = MultiDimensionalBasisFunction(A, degs, interp_pts, [xivals[i],etavals[j]])

    # contour plot
    if contours:
        fig, ax = plt.subplots()
        surf = ax.contourf(Eta,Xi,Z,levels=100,cmap=matplotlib.cm.jet)
        ax.set_xlabel(r"$\xi$")
        ax.set_ylabel(r"$\eta$")
        fig.colorbar(surf)
        plt.show()
    # 3D surface plot
    else:
        fig, ax = plt.subplots(subplot_kw={"projection": "3d"})
        surf = ax.plot_surface(Eta, Xi, Z, cmap=matplotlib.cm.jet,
                       linewidth=0, antialiased=False)
        ax.set_xlabel(r"$\xi$")
        ax.set_ylabel(r"$\eta$")
        ax.set_zlabel(r"$N(\xi,\eta)$")
        plt.show()

"""Plot two-dimensional basis functions of the following polynomial degrees over the interval
[-1,1] using the PlotTwoDimensionalParentBasisFunction code given to you. You can plot
these either as surface plots or as contour plots, depending on your preference. Do this for
– Polynomials of degree [1,1]
– Polynomials of degree [2,1]
– Polynomials of degree [2,2]
– Polynomials of degree [3,3]
"""

A = 2
degs = [1,1]
PlotTwoDimensionalParentBasisFunction(A,degs,npts = 101,contours = True)
PlotTwoDimensionalParentBasisFunction(A,degs,npts = 101,contours = False)

A = 2
degs = [2,1]
PlotTwoDimensionalParentBasisFunction(A,degs,npts = 101,contours = True)
PlotTwoDimensionalParentBasisFunction(A,degs,npts = 101,contours = False)

A = 2
degs = [2,2]
PlotTwoDimensionalParentBasisFunction(A,degs,npts = 101,contours = True)
PlotTwoDimensionalParentBasisFunction(A,degs,npts = 101,contours = False)

A = 2
degs = [3,3]
PlotTwoDimensionalParentBasisFunction(A,degs,npts = 101,contours = True)
PlotTwoDimensionalParentBasisFunction(A,degs,npts = 101,contours = False)

"""# Problem 2"""

#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Sep 23 21:18:02 2024

@author: kendrickshepherd
"""

import sys
import numpy as np
import math
import matplotlib
from matplotlib import pyplot as plt

# IMPORT (or copy) your code from HW3 here
# which evaluated a Lagrane polynomial basis function


## Code From HW 3 ##


# Given a set of points, pts, to interpolate
# and a polynomial degree, this function will
# evaluate the a-th basis function at the
# location xi

def LagrangeBasisEvaluation(p,pts,xi,a):
    # ensure valid input
    if (p+1 != len(pts)):
        sys.exit("The number of input points for interpolating must be the same as one plus the polynomial degree for interpolating")

    # ensure 'pts' is unique and in ascending order
    pts_unique = sorted(set(pts))

    val = 1
    for b in range(0,p+1):
        if b != a:
            val *= (xi-pts_unique[b])/(pts_unique[a]-pts_unique[b])
    return val

    # complete this code and return an appropriate value
    # as given in Hughes Equation 3.6.1

# Plot the Lagrange polynomial basis functions
# COMMENT THIS CODE
def PlotLagrangeBasisFunctions(p,pts,n_samples = 101):

    # ensure 'pts' is unique and in ascending order
    pts_unique = sorted(set(pts))

    # Makes 'xis' into 101 evenly spaced intervals starting at the minimum value
    # in the list 'pts' and ending at the maximum value of 'pts'
    xis = np.linspace(min(pts),max(pts),n_samples)
    # Creates a single figure with a single set of axes.
    fig, ax = plt.subplots()
    # Starts a 'for' loop that will march the variable 'a' from zero to 'p+1'
    # where 'p+1' is the polynomial degree + 1
    for a in range(0,p+1):
        # Creates an empty list called 'vals'
        vals = []
        # Starts a 'for' loop where the variable 'xi' is marched through each
        # interval of 'xis'
        for xi in xis:
            # Since 'vals' is an empty list, this builds a list of the output
            # from the 'LagrangeBasisEvaluation' equation, which computes the
            # value of the lagrange basis polynomial of degree 'a' at 'xi'
            vals.append(LagrangeBasisEvaluation(p, pts, xi, a))
        # Generates a plot where 'xis' is the x-value and 'vals' is the y-value
        plt.plot(xis,vals)
    # Adds a dashed grid to the plot generated previously
    ax.grid(linestyle='--')

# Interpolate two-dimensional data
def InterpolateFunction(p,pts2D,n_samples = 101):
    # Insert appropriate text here, as described
    # in the homework prompt

    # Separate the 'pts2D' array into x and y coordinates
    pts = pts2D[:,0]
    coeffs = pts2D[:,1]

    # Create an evenly distributed list of the x coordinates ('pts')
    xis = np.linspace(min(pts),max(pts),n_samples)

    # Create an array of zeros in the same dimension as xis
    ys = np.zeros(len(xis))

    # Create a for loop that goes through every index in the list xis then
    # extract the i-th value of xis
    for i in range(len(xis)):
      xi = xis[i]
      L = 0
      # Create a nested for loop to evaluate every p+1 of the Lagrange polynomial
      # basis functions at point xi
      for a in range(min(pts),p+1):
        LBE = LagrangeBasisEvaluation(p,pts,xi,a)
        L += LBE * coeffs[a]
      # Multiply the value of the basis function evaluated at xi by its corresponding
      # y coefficient from 'coeffs'. Add this quantity into the 'ys' value corresponding
      # to index xi
      ys[i] += L

    fig, ax = plt.subplots()
    plt.plot(xis,ys)
    plt.scatter(pts, coeffs,color='r')



## ^^Code From HW 3^^ ##




# x(\xi) = \sum_{a=0}^p x_a * N_a(\xi)
def XMap(deg,spatial_pts,interp_pts,xi):
    x = 0
    for a in range(len(spatial_pts)):
      x += spatial_pts[a] * LagrangeBasisEvaluation(deg,interp_pts,xi,a)
    return x

def PlotXMap(deg,spatial_pts,interp_pts, npts=101, contours=True):
    # parametric points to evaluate in Lagrange basis function
    xi_vals = np.linspace(interp_pts[0],interp_pts[-1],npts)

    # evaluate and plot as a line
    if not contours:
        xs = []
        for i in range(0,len(xi_vals)):
            xi = xi_vals[i]
            xs.append(XMap(deg,spatial_pts,interp_pts,xi))

        plt.plot(xi_vals,xs)
        plt.show()

    # evaluate as a contour plot
    else:
        Xi,Xi2 = np.meshgrid(xi_vals,[-0.2,0.2])
        Z = np.zeros(Xi.shape)
        for i in range(0,len(xi_vals)):
            xi = xi_vals[i]
            x = XMap(deg,spatial_pts,interp_pts,xi)
            for j in range(0,2):
                Z[j,i] = x

        fig, ax = plt.subplots()
        surf = ax.contourf(Z,Xi2,Xi,levels=100,cmap=matplotlib.cm.binary)
        ax.set_xlabel(r"$x$")
        ax.yaxis.set_ticklabels([])
        fig.colorbar(surf)
        plt.show()

"""### Use PlotXMap to see how XMap maps from the parent domain ([-1,1]) into a spatial domain. Do this for the following input:
### – p = 1, {xa} = {0, 1}, {ξa} = {−1, 1}

### – p = 2, {xa} = {0.5, 1, 1.5}, {ξa} = {−1, 0, 1}

### – p = 2, {xa} = {0.5, 0.7, 1.5}, {ξa} = {−1, −0.6, 1}

### – p = 2, {xa} = {0.5, 0.7, 1.5}, {ξa} = {−1, 0, 1}

### Again, you can use either contour plots or line plots to help visualize what is happening with your function.
"""

deg = 1
spatial_pts = np.array([0,1])
interp_pts = np.array([-1,1])
PlotXMap(deg,spatial_pts,interp_pts, npts=101, contours=True)
PlotXMap(deg,spatial_pts,interp_pts, npts=101, contours=False)

deg = 2
spatial_pts = np.array([0.5,1,1.5])
interp_pts = np.array([-1,0,1])
PlotXMap(deg,spatial_pts,interp_pts, npts=101, contours=True)
PlotXMap(deg,spatial_pts,interp_pts, npts=101, contours=False)

deg = 2
spatial_pts = np.array([0.5,0.7,1.5])
interp_pts = np.array([-1,-0.6,1])
PlotXMap(deg,spatial_pts,interp_pts, npts=101, contours=True)
PlotXMap(deg,spatial_pts,interp_pts, npts=101, contours=False)

deg = 2
spatial_pts = np.array([0.5,0.7,1.5])
interp_pts = np.array([-1,0,1])
PlotXMap(deg,spatial_pts,interp_pts, npts=101, contours=True)
PlotXMap(deg,spatial_pts,interp_pts, npts=101, contours=False)

"""### When is the mapping xe(ξ) linear? When is this map transition from the interval [−1, 1] to the input spatial element in a manner that correctly transforms points for Gaussian quadrature?

The mapping xe(ξ) is linear for the first (3) mappings from the parametric domain to the spacial domain. When the mapping is linear the map transition from the parent domain to the spacial domain is done in a manner that the points are correctly transformed for Gaussian quadrature.
"""