# -*- coding: utf-8 -*-
"""CE507-HW8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ndWNJF354fkrzOpRl28-iZZTPjZRVT6Y
"""

#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Sep 25 11:06:03 2024

@author: kendrickshepherd
"""

import sys
import numpy as np
import math
import matplotlib
from matplotlib import pyplot as plt

# Depending on your approach,
# You may need to import information from HW3 and/or
# HW6 to load in your unidimensional and multidimensional
# Lagrange basis function code


## Code From HW 6 ##


## Code From HW 3 ##

# Given a set of points, pts, to interpolate
# and a polynomial degree, this function will
# evaluate the a-th basis function at the
# location xi

def LagrangeBasisEvaluation(p,pts,xi,a):
    # ensure valid input
    if (p+1 != len(pts)):
        sys.exit("The number of input points for interpolating must be the same as one plus the polynomial degree for interpolating")

    # ensure 'pts' is unique and in ascending order
    pts_unique = sorted(set(pts))

    val = 1
    for b in range(0,p+1):
        if b != a:
            val *= (xi-pts_unique[b])/(pts_unique[a]-pts_unique[b])
    return val

    # complete this code and return an appropriate value
    # as given in Hughes Equation 3.6.1

# Plot the Lagrange polynomial basis functions
# COMMENT THIS CODE
def PlotLagrangeBasisFunctions(p,pts,n_samples = 101):

    # ensure 'pts' is unique and in ascending order
    pts_unique = sorted(set(pts))

    # Makes 'xis' into 101 evenly spaced intervals starting at the minimum value
    # in the list 'pts' and ending at the maximum value of 'pts'
    xis = np.linspace(min(pts),max(pts),n_samples)
    # Creates a single figure with a single set of axes.
    fig, ax = plt.subplots()
    # Starts a 'for' loop that will march the variable 'a' from zero to 'p+1'
    # where 'p+1' is the polynomial degree + 1
    for a in range(0,p+1):
        # Creates an empty list called 'vals'
        vals = []
        # Starts a 'for' loop where the variable 'xi' is marched through each
        # interval of 'xis'
        for xi in xis:
            # Since 'vals' is an empty list, this builds a list of the output
            # from the 'LagrangeBasisEvaluation' equation, which computes the
            # value of the lagrange basis polynomial of degree 'a' at 'xi'
            vals.append(LagrangeBasisEvaluation(p, pts, xi, a))
        # Generates a plot where 'xis' is the x-value and 'vals' is the y-value
        plt.plot(xis,vals)
    # Adds a dashed grid to the plot generated previously
    ax.grid(linestyle='--')

# Interpolate two-dimensional data
def InterpolateFunction(p,pts2D,n_samples = 101):
    # Insert appropriate text here, as described
    # in the homework prompt

    # Separate the 'pts2D' array into x and y coordinates
    pts = pts2D[:,0]
    coeffs = pts2D[:,1]

    # Create an evenly distributed list of the x coordinates ('pts')
    xis = np.linspace(min(pts),max(pts),n_samples)

    # Create an array of zeros in the same dimension as xis
    ys = np.zeros(len(xis))

    # Create a for loop that goes through every index in the list xis then
    # extract the i-th value of xis
    for i in range(len(xis)):
      xi = xis[i]
      L = 0
      # Create a nested for loop to evaluate every p+1 of the Lagrange polynomial
      # basis functions at point xi
      for a in range(min(pts),p+1):
        LBE = LagrangeBasisEvaluation(p,pts,xi,a)
        L += LBE * coeffs[a]
      # Multiply the value of the basis function evaluated at xi by its corresponding
      # y coefficient from 'coeffs'. Add this quantity into the 'ys' value corresponding
      # to index xi
      ys[i] += L

    fig, ax = plt.subplots()
    plt.plot(xis,ys)
    plt.scatter(pts, coeffs,color='r')



## ^^Code From HW 3^^ ##



# higher-dimensional basis function with multi-index
def MultiDimensionalBasisFunctionIdxs(idxs,degs,interp_pts,xis):
    x = 0
    for a in range(0,degs+1):
        x += spatial_pts[a] * LagrangeBasisEvaluation(degs,interp_pts,xis,a)
    return

# higher-dimensional basis function with single index
def MultiDimensionalBasisFunction(A,degs,interp_pts,xis):
    multi_indxs = []
    for i in range(len(degs)):
        multi_indxs.append(A % degs[i])
        A = A // degs[i]

    val = 1
    for i in range(0,len(multi_indxs)):
        val *= LagrangeBasisEvaluation(degs[i],interp_pts[i],xis[i],multi_indxs[i])
    return val



## ^^ Code from Hw 6 ^^ ##



# input polynomial degree, p,
#       interpolation points, pts,
#       the point of evaluation, xi,
#   and the basis fnction index, a


def LagrangeBasisParamDervEvaluation(p,pts,xi,a):
    sum_val = 0
    # part_val = 1
    for j in range (0,p+1):
        if j==a:
            continue
        else:
            part_val = 1
            for b in range (0,p+1):
                if b!=j and b!=a:
                    part_val *= ((xi-pts[b])/(pts[a]-pts[b]))
                    
            sum_val += part_val / (pts[a]-pts[j])
        
    return sum_val
def LagrangeBasisParamDervEvaluation(p,pts,xi,a):
    sum = 0
    product = 1
    for j in range(0, p + 1):
      if j != a:
        sum += 1 / (pts[a] - pts[j])
      for b in range(0, p + 1):
        if b != a:
            product *= (xi - pts[b]) / (pts[a] - pts[b])
    return product * sum

# you may want to create a function here that
# converts from a single index, A, and a set of
# polynomial degrees into a multi-index indicating
# the indices of the univariate lagrange polynomials
#
# you will need this functionality, though you do
# not need to complete this function for full credit
def GlobalToLocalIdxs(A,degs):
    array = []
    for deg in degs:
        array.append(A % (deg + 1))
        A //= (deg + 1)
    return array

# evaluate the partial derivative of a nD lagrange
# basis function of index A in the "dim" dimension
# (e.g. derivative in xi is 0, in eta is 1)
def LagrangeBasisDervParamMultiD(A,degs,interp_pts,xis,dim):
    n = len(degs)  # Number of dimensions
    derivative = 1.0

    # Loop over each dimension
    for d in range(n):
        if d == dim:
            product = 1.0
            for j in range(degs[d] + 1):
                if j != A:
                    product *= (xis[d] - interp_pts[d][j]) / (interp_pts[d][A] - interp_pts[d][j])
            derivative *= product / (interp_pts[d][A] - interp_pts[d][A]) if (interp_pts[d][A] != interp_pts[d][A]) else 1
        else:
            product = 1.0
            for j in range(degs[d] + 1):
                if j != A:
                    product *= (xis[d] - interp_pts[d][j]) / (interp_pts[d][A] - interp_pts[d][j])
            derivative *= product

    return derivative

# Plot the Lagrange polynomial basis function
# derivatives
def PlotLagrangeBasisDerivatives(p,pts,n_samples = 101):
    xis = np.linspace(min(pts),max(pts),n_samples)
    fig, ax = plt.subplots()
    for a in range(0,p+1):
        vals = []
        for xi in xis:
            vals.append(LagrangeBasisParamDervEvaluation(p, pts, xi, a))

        plt.plot(xis,vals)
    ax.grid(linestyle='--')

# plot a basis function defined on a parent
# domain; this is similar to what was
# in a previous homework, but slightly generalized
def PlotTwoDBasisFunctionParentDomain(A,degs,interp_pts,dim,npts=21,contours=False):
    xivals = np.linspace(interp_pts[0][0],interp_pts[0][-1],npts+1)
    etavals = np.linspace(interp_pts[1][0],interp_pts[1][-1],npts)

    Xi,Eta = np.meshgrid(xivals,etavals)
    Z = np.zeros(Xi.shape)

    for i in range(0,len(xivals)):
        for j in range(0,len(etavals)):
            xi_vals = [xivals[i],etavals[j]]
            if dim < 0:
                # if you imported your multidimensional
                # lagrange basis function code as
                # module "m_basis", uncomment the line below
                Z[j,i] = m_basis.MultiDimensionalBasisFunction(A,degs,interp_pts,xi_vals)
                continue
            else:
                Z[j,i] = LagrangeBasisDervParamMultiD(A,degs,interp_pts,xi_vals,dim)

    if contours:
        fig, ax = plt.subplots()
        surf = ax.contourf(Xi,Eta,Z,levels=100,cmap=matplotlib.cm.jet)
        ax.set_xlabel(r"$\xi$")
        ax.set_ylabel(r"$\eta$")
        fig.colorbar(surf)
        plt.show()
    else:
        fig, ax = plt.subplots(subplot_kw={"projection": "3d"})
        surf = ax.plot_surface(Xi, Eta, Z, cmap=matplotlib.cm.jet,
                       linewidth=0, antialiased=False)
        ax.set_xlabel(r"$\xi$")
        ax.set_ylabel(r"$\eta$")
        ax.set_zlabel(r"$\frac{\partial N_A}{\partial xi_%d}$" % dim)
        plt.show()

"""# Problem 3"""

p = 2
pts = [-1, 0, 1]
PlotLagrangeBasisDerivatives(p,pts,n_samples = 101)

"""# Problem 4"""

A = 2
degs = [2,2]
interp_pts = [[-1,0,1],[-1,0,1]]
dim = 2
PlotTwoDBasisFunctionParentDomain(A,degs,interp_pts,dim,npts=21,contours=True)
PlotTwoDBasisFunctionParentDomain(A,degs,interp_pts,dim,npts=21,contours=False)